/**
 * ============================================================
 *  FUNNY SOUNDS — VS Code Extension Guide
 * ============================================================
 *
 *  This file is a developer guide written in TypeScript.
 *  It explains how the extension works, how to set it up,
 *  and how to customize it.
 */

// ─────────────────────────────────────────────────────────────
//  1. WHAT DOES THIS EXTENSION DO?
// ─────────────────────────────────────────────────────────────

/**
 * Funny Sounds listens to your VS Code terminal output in real-time.
 * Whenever a line containing an error keyword appears (e.g. "Error",
 * "FATAL", "SyntaxError"), it plays a sound so you *hear* the failure
 * instantly — even if the terminal is hidden or you're looking at
 * another tab.
 *
 * Features:
 *  - Plays a "boing" sound on terminal errors (default .wav included)
 *  - Use your own sound file (.wav, .mp3, .ogg)
 *  - Configurable error patterns, volume, and cooldown
 *  - Status bar toggle to quickly enable/disable
 *  - Works on Windows, macOS, and Linux
 */

// ─────────────────────────────────────────────────────────────
//  2. PROJECT STRUCTURE
// ─────────────────────────────────────────────────────────────

interface ProjectStructure {
  "package.json": "Extension manifest — commands, settings, metadata";
  "tsconfig.json": "TypeScript compiler configuration";
  "src/extension.ts": "Entry point — activation, commands, terminal listener";
  "src/soundPlayer.ts": "Utility class that plays audio cross-platform";
  "sounds/error.wav": "Default 'boing' error sound (auto-generated)";
  "out/": "Compiled JavaScript (generated by `npm run compile`)";
  "GUIDE.ts": "This file — developer guide";
}

// ─────────────────────────────────────────────────────────────
//  3. GETTING STARTED
// ─────────────────────────────────────────────────────────────

/**
 * STEP 1 — Install dependencies:
 *
 *   npm install
 *
 * STEP 2 — Compile TypeScript:
 *
 *   npm run compile
 *
 * STEP 3 — Test in VS Code:
 *
 *   Press F5 in VS Code to open an Extension Development Host.
 *   Open a terminal in the new window and type a command that
 *   produces an error, for example:
 *
 *     node -e "throw new Error('boom')"
 *
 *   You should hear the error sound!
 *
 * STEP 4 — Package for distribution (optional):
 *
 *   npm install -g @vscode/vsce
 *   vsce package
 *
 *   This creates a `.vsix` file you can install anywhere with:
 *
 *     code --install-extension funny-sounds-1.0.0.vsix
 */

// ─────────────────────────────────────────────────────────────
//  4. AVAILABLE COMMANDS (Command Palette)
// ─────────────────────────────────────────────────────────────

enum Commands {
  /** Enable error sound playback */
  Enable = "funnySounds.enable",

  /** Disable error sound playback */
  Disable = "funnySounds.disable",

  /** Play the current sound once (for testing) */
  TestSound = "funnySounds.testSound",

  /** Open a file picker to choose a custom sound file */
  SelectSound = "funnySounds.selectSound",
}

// ─────────────────────────────────────────────────────────────
//  5. EXTENSION SETTINGS
// ─────────────────────────────────────────────────────────────

interface FunnySoundsSettings {
  /**
   * Master switch.
   * @default true
   */
  "funnySounds.enabled": boolean;

  /**
   * Path to a custom sound file (.wav / .mp3 / .ogg).
   * Leave empty to use the built-in "boing" sound.
   * @default ""
   */
  "funnySounds.soundFilePath": string;

  /**
   * Volume level from 0 (silent) to 100 (full).
   * @default 50
   */
  "funnySounds.volume": number;

  /**
   * Strings to match in terminal output. If any pattern is found
   * in a terminal write event, the sound plays.
   * @default ["error","Error","ERROR","fatal","FATAL", ...]
   */
  "funnySounds.errorPatterns": string[];

  /**
   * Minimum milliseconds between consecutive sound plays.
   * Prevents rapid-fire audio when many errors print at once.
   * @default 2000
   */
  "funnySounds.cooldownMs": number;
}

// ─────────────────────────────────────────────────────────────
//  6. HOW THE TERMINAL LISTENER WORKS
// ─────────────────────────────────────────────────────────────

/**
 * The core mechanism uses the VS Code API:
 *
 *   vscode.window.onDidWriteTerminalData(event => { ... })
 *
 * This event fires every time text is written to any terminal.
 * The extension checks `event.data` against the configured
 * error patterns. If a match is found, it calls `SoundPlayer.play()`.
 *
 * The SoundPlayer uses platform-specific commands:
 *
 *   Windows : PowerShell System.Media.SoundPlayer
 *   macOS   : afplay
 *   Linux   : paplay / aplay / ffplay (first available)
 *
 * A cooldown timer prevents audio spam when errors cascade.
 */

// ─────────────────────────────────────────────────────────────
//  7. USING YOUR OWN SOUND
// ─────────────────────────────────────────────────────────────

/**
 * Option A — Via the command palette:
 *   1. Press Ctrl+Shift+P (or Cmd+Shift+P on macOS)
 *   2. Run "Funny Sounds: Select Custom Sound File"
 *   3. Pick any .wav, .mp3, or .ogg file
 *
 * Option B — Via settings.json:
 *   {
 *     "funnySounds.soundFilePath": "C:/Sounds/bruh.wav"
 *   }
 *
 * Option C — Replace the default sound:
 *   Overwrite `sounds/error.wav` with your own .wav file.
 */

// ─────────────────────────────────────────────────────────────
//  8. CUSTOMIZING ERROR PATTERNS
// ─────────────────────────────────────────────────────────────

/**
 * Add or remove patterns in your VS Code settings:
 *
 *   "funnySounds.errorPatterns": [
 *     "error",
 *     "Error",
 *     "FAILED",
 *     "panic",             // Rust / Go panics
 *     "Traceback",         // Python stack traces
 *     "COMPILATION FAILED" // Gradle builds
 *   ]
 *
 * Patterns are simple substring matches (not regex) for
 * maximum performance since terminal output can be very fast.
 */

// ─────────────────────────────────────────────────────────────
//  9. ARCHITECTURE OVERVIEW
// ─────────────────────────────────────────────────────────────

/**
 *  ┌─────────────────────┐
 *  │   VS Code Terminal   │
 *  │   (any shell)        │
 *  └────────┬────────────┘
 *           │  onDidWriteTerminalData
 *           v
 *  ┌─────────────────────┐
 *  │   extension.ts       │
 *  │   - pattern matching │
 *  │   - command handlers │
 *  │   - status bar       │
 *  └────────┬────────────┘
 *           │  play()
 *           v
 *  ┌─────────────────────┐
 *  │   soundPlayer.ts     │
 *  │   - cooldown check   │
 *  │   - platform detect  │
 *  │   - exec audio cmd   │
 *  └────────┬────────────┘
 *           │
 *           v
 *  ┌─────────────────────┐
 *  │   OS Audio System    │
 *  │   (PowerShell /      │
 *  │    afplay / paplay)  │
 *  └─────────────────────┘
 */

// ─────────────────────────────────────────────────────────────
// 10. TROUBLESHOOTING
// ─────────────────────────────────────────────────────────────

/**
 * Q: I don't hear any sound!
 * A: 1. Check the status bar shows "Funny Sounds" with an unmute icon.
 *    2. Run "Funny Sounds: Test Sound" from the command palette.
 *    3. Make sure `sounds/error.wav` exists or a custom path is set.
 *    4. On Linux, ensure `paplay`, `aplay`, or `ffplay` is installed.
 *
 * Q: Sound plays too often!
 * A: Increase the cooldown:
 *    "funnySounds.cooldownMs": 5000
 *
 * Q: Sound doesn't play for my framework's errors!
 * A: Add the error text to "funnySounds.errorPatterns" in settings.
 *
 * Q: How do I completely uninstall?
 * A: Run: code --uninstall-extension funny-sounds
 *    Or find it in Extensions sidebar → Uninstall.
 */

// ─────────────────────────────────────────────────────────────
// 11. DEVELOPMENT TIPS
// ─────────────────────────────────────────────────────────────

/**
 * - Run `npm run watch` for live-recompilation during development.
 * - Use the Debug Console (F5 launch) to see `console.log` output.
 * - The `onDidWriteTerminalData` API is a proposed API in older
 *   VS Code versions. It is stable from VS Code 1.80+.
 * - To add new sounds for different error severities, extend the
 *   SoundPlayer class to accept a sound category parameter.
 */

// That's it! Happy coding with sounds. 🔊

export { Commands, FunnySoundsSettings, ProjectStructure };
